# Generated by Django 6.0.1 on 2026-02-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='candidate_email',
        ),
    ]
