# Generated by Django 6.0.1 on 2026-02-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resume_app', '0003_resume_job_alter_resume_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_id',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ats_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_app.resume'),
        ),
    ]
