from django.urls import path
from .views import (
    MeView,
    ResumeUploadView,
    GenerateATSResumeView,
    BuildATSResumeView,
    RecommendedJobsView,
    RankedCandidatesView,
    MyApplicationsView,
    CandidateDashboardView,
    CandidateDashboardSummaryView,
    RecruiterDashboardView,
    ActivityView,
    NotificationView,
    UpdateApplicationStatusView,
    TopCandidatesView,
    ShortlistedCandidatesView,
    RejectedCandidatesView,
    AIResumeFeedbackView,
    RecentApplicationsView,
    FeedbackCreateView,
)

urlpatterns = [
    path("me/", MeView.as_view()),
    path("upload/", ResumeUploadView.as_view(), name="resume-upload"),
    path("analyze/", ResumeUploadView.as_view(), name="resume-analyze"),
    path("generate-ats/<int:resume_id>/", GenerateATSResumeView.as_view()),
    path("build-resume-pdf/", BuildATSResumeView.as_view()),
    path("recommend-jobs/<int:resume_id>/", RecommendedJobsView.as_view()),
    path("ranked-candidates/<int:job_id>/", RankedCandidatesView.as_view()),
    path("my-applications/", MyApplicationsView.as_view()),
    path("candidate/dashboard/", CandidateDashboardView.as_view()),
    path("recruiter/dashboard/", RecruiterDashboardView.as_view()),
    path("recruiter/top-candidates/<int:job_id>/", TopCandidatesView.as_view()),
    path("recruiter/shortlisted/<int:job_id>/", ShortlistedCandidatesView.as_view()),
    path("recruiter/rejected/<int:job_id>/", RejectedCandidatesView.as_view()),
    path("application-status/<int:application_id>/", UpdateApplicationStatusView.as_view()),
    path("activity/", ActivityView.as_view()),
    path("notifications/", NotificationView.as_view()),
    path("ai-feedback/", AIResumeFeedbackView.as_view()),
    path("recent-applications/", RecentApplicationsView.as_view()),
    path("feedback/", FeedbackCreateView.as_view()),
]
